// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUWlbWw6tVM7jMTDgGPqguAAN90ssp3fQ',
    appId: '1:1014116003942:web:6a5c09d4312d324084fda7',
    messagingSenderId: '1014116003942',
    projectId: 'field-25c5e',
    authDomain: 'field-25c5e.firebaseapp.com',
    storageBucket: 'field-25c5e.firebasestorage.app',
    measurementId: 'G-EQYP3MH0VT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaRPEV1XncuGoBJWPMAuVqTANcF2mEfig',
    appId: '1:1014116003942:android:a4c0e997b549a9c884fda7',
    messagingSenderId: '1014116003942',
    projectId: 'field-25c5e',
    storageBucket: 'field-25c5e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0ZyoNrytJFYebLPgJz8PtX_ELCGgiBmI',
    appId: '1:1014116003942:ios:396cf525a95f4dba84fda7',
    messagingSenderId: '1014116003942',
    projectId: 'field-25c5e',
    storageBucket: 'field-25c5e.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0ZyoNrytJFYebLPgJz8PtX_ELCGgiBmI',
    appId: '1:1014116003942:ios:396cf525a95f4dba84fda7',
    messagingSenderId: '1014116003942',
    projectId: 'field-25c5e',
    storageBucket: 'field-25c5e.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUWlbWw6tVM7jMTDgGPqguAAN90ssp3fQ',
    appId: '1:1014116003942:web:6ab8e780c00f10d884fda7',
    messagingSenderId: '1014116003942',
    projectId: 'field-25c5e',
    authDomain: 'field-25c5e.firebaseapp.com',
    storageBucket: 'field-25c5e.firebasestorage.app',
    measurementId: 'G-00CEH7QCMG',
  );
}
